### ISSUE TITLE
Notice : Validation issue on line 197 and 205

### ISSUE THREAD

**Issue by SeeTwoDev** [thirtybees/ctconfiguration#1]
change 
if ($field['cast'] && in_array($field['cast'], $castFunctions)) {

to
if (array_key_exists('cast',$field) &&  $field['cast'] && in_array($field['cast'], $castFunctions)) {

**Comment by Traumflug** [comment]
Looking at the code, this was fixed with release 1.0.1 already, just in a slightly different way.

Anyways, thanks for the report! If the problem persists, please don't hesitate to open another issue.
